import {
  GameMissionInterface,
  SpecialNotesEnum,
  TaskTokenEnum,
} from './interfaces';

export const missions: GameMissionInterface[] = [
  {
    id: 1,
    note: '',
    taskCards: 1,
    taskTokens: [],
    taskNotes: [],
  },
  {
    id: 2,
    note: '',
    taskCards: 2,
    taskTokens: [],
    taskNotes: [],
  },
  {
    id: 3,
    taskCards: 2,
    note: '',
    taskTokens: [TaskTokenEnum.TOKEN_FIRST, TaskTokenEnum.TOKEN_SECOND],
    taskNotes: [],
  },
  {
    id: 4,
    note: '',
    taskCards: 3,
    taskTokens: [],
    taskNotes: [],
  },
  {
    id: 5,
    note:
      'Der Kommandant fragt jedem nach seinem Befinden. Geantwortet mit "gut" oder "schlecht". Der Kommandant entscheidet wer krank ist. Diese Person darf keinen einzigen Stich gewinnen.',
    taskCards: 0,
    taskTokens: [],
    taskNotes: [],
  },
  {
    id: 6,
    note: '',
    taskCards: 3,
    taskTokens: [TaskTokenEnum.TOKEN_BEFORE_1, TaskTokenEnum.TOKEN_BEFORE_2],
    taskNotes: [SpecialNotesEnum.RADIO_HOLE],
  },
  {
    id: 7,
    note: '',
    taskCards: 3,
    taskTokens: [TaskTokenEnum.TOKEN_LAST],
    taskNotes: [],
  },
  {
    id: 8,
    note: '',
    taskCards: 3,
    taskTokens: [
      TaskTokenEnum.TOKEN_FIRST,
      TaskTokenEnum.TOKEN_SECOND,
      TaskTokenEnum.TOKEN_THIRD,
    ],
    taskNotes: [],
  },
  {
    id: 9,
    note: 'Eine 1er Karte muss einen Stich gewinnen.',
    taskCards: 1,
    taskTokens: [],
    taskNotes: [],
  },
  {
    id: 10,
    note: '',
    taskCards: 4,
    taskTokens: [],
    taskNotes: [],
  },
  {
    id: 11,
    note:
      'Ein Crewmitglied kann nicht kommunizieren. Der Kommandant bestimmt das Crewmitglied.',
    taskCards: 4,
    taskTokens: [TaskTokenEnum.TOKEN_FIRST],
    taskNotes: [],
  },
  {
    id: 12,
    note:
      'Nach dem 1. Stich muss jeder eine zufällige Karte des Crewmitglieds rechts von sich ziehen.',
    taskCards: 4,
    taskTokens: [TaskTokenEnum.TOKEN_LAST],
    taskNotes: [],
  },
  {
    id: 13,
    note: 'Ihr müsst mit jeder Raketenkarte einen Stich gewinnen.',
    taskCards: 0,
    taskTokens: [],
    taskNotes: [],
  },
  {
    id: 14,
    note: '',
    taskCards: 4,
    taskTokens: [
      TaskTokenEnum.TOKEN_BEFORE_1,
      TaskTokenEnum.TOKEN_BEFORE_2,
      TaskTokenEnum.TOKEN_BEFORE_3,
    ],
    taskNotes: [SpecialNotesEnum.RADIO_HOLE],
  },
  {
    id: 15,
    note: '',
    taskCards: 4,
    taskTokens: [
      TaskTokenEnum.TOKEN_FIRST,
      TaskTokenEnum.TOKEN_SECOND,
      TaskTokenEnum.TOKEN_THIRD,
      TaskTokenEnum.TOKEN_FOURTH,
    ],
    taskNotes: [],
  },
  {
    id: 16,
    note: 'Ihr dürft keinen Stich mit einer 9er Karte gewinnen.',
    taskCards: 0,
    taskTokens: [],
    taskNotes: [],
  },
  {
    id: 17,
    note: '9er Karten gewinnen noch immer keinen Stich.',
    taskCards: 2,
    taskTokens: [],
    taskNotes: [],
  },
  {
    id: 18,
    note: '',
    taskCards: 5,
    taskTokens: [],
    taskNotes: [SpecialNotesEnum.RADIO_INTERFERENCE],
    radioInterferenceAfter: 2,
  },
  {
    id: 19,
    note: '',
    taskCards: 5,
    taskTokens: [TaskTokenEnum.TOKEN_FIRST],
    taskNotes: [SpecialNotesEnum.RADIO_INTERFERENCE],
    radioInterferenceAfter: 3,
  },
  {
    id: 20,
    note: '',
    taskCards: 2,
    taskTokens: [],
    taskNotes: [SpecialNotesEnum.COMMANDER_DECISION],
  },
  {
    id: 21,
    note: '',
    taskCards: 5,
    taskTokens: [TaskTokenEnum.TOKEN_FIRST, TaskTokenEnum.TOKEN_SECOND],
    taskNotes: [SpecialNotesEnum.RADIO_HOLE],
  },
  {
    id: 22,
    note: '',
    taskCards: 5,
    taskTokens: [
      TaskTokenEnum.TOKEN_BEFORE_1,
      TaskTokenEnum.TOKEN_BEFORE_2,
      TaskTokenEnum.TOKEN_BEFORE_3,
      TaskTokenEnum.TOKEN_BEFORE_4,
    ],
    taskNotes: [],
  },
  {
    id: 23,
    note:
      'Bevor die Aufträge verteilt werden dürft ihr zwei Auftragsplättchen tauschen. Entscheidet gemeinsam, aber verratet nichts über eure Handkarten.',
    taskCards: 5,
    taskTokens: [
      TaskTokenEnum.TOKEN_FIRST,
      TaskTokenEnum.TOKEN_SECOND,
      TaskTokenEnum.TOKEN_THIRD,
      TaskTokenEnum.TOKEN_FOURTH,
      TaskTokenEnum.TOKEN_FIFTH,
    ],
    taskNotes: [],
  },
  {
    id: 24,
    note: '',
    taskCards: 6,
    taskTokens: [],
    taskNotes: [SpecialNotesEnum.COMMANDER_DISTRIBUTION],
  },
  {
    id: 25,
    note:
      'Spielt ihr zu fünft darf ab jetzt die Zusatzregel für 5 Crewmitglieder genutzt werden.',
    taskCards: 6,
    taskTokens: [TaskTokenEnum.TOKEN_BEFORE_1, TaskTokenEnum.TOKEN_BEFORE_2],
    taskNotes: [SpecialNotesEnum.RADIO_HOLE],
    specialRule: true,
  },
  {
    id: 26,
    note: 'Zwei 1er Karten müssen einen Stich gewinnen',
    taskCards: 0,
    taskTokens: [],
    taskNotes: [],
  },
  {
    id: 27,
    note: '',
    taskCards: 3,
    taskTokens: [],
    specialRule: true,
    taskNotes: [SpecialNotesEnum.COMMANDER_DECISION],
  },
  {
    id: 28,
    note: '',
    taskCards: 6,
    taskTokens: [TaskTokenEnum.TOKEN_FIRST, TaskTokenEnum.TOKEN_LAST],
    taskNotes: [SpecialNotesEnum.RADIO_INTERFERENCE],
    radioInterferenceAfter: 3,
    specialRule: true,
  },
  {
    id: 29,
    note:
      'Zu keinen Zeitpunkt darf ein Crewmitgleid 2 Stiche mehr haben als ein anderes.',
    taskCards: 0,
    taskTokens: [],
    taskNotes: [SpecialNotesEnum.RADIO_HOLE],
  },
  {
    id: 30,
    note: '',
    taskCards: 6,
    taskTokens: [
      TaskTokenEnum.TOKEN_BEFORE_1,
      TaskTokenEnum.TOKEN_BEFORE_2,
      TaskTokenEnum.TOKEN_BEFORE_3,
    ],
    specialRule: true,
    taskNotes: [SpecialNotesEnum.RADIO_INTERFERENCE],
    radioInterferenceAfter: 2,
  },
  {
    id: 31,
    note: '',
    taskCards: 6,
    taskTokens: [
      TaskTokenEnum.TOKEN_FIRST,
      TaskTokenEnum.TOKEN_SECOND,
      TaskTokenEnum.TOKEN_THIRD,
    ],
    specialRule: true,
    taskNotes: [],
  },
  {
    id: 32,
    note: '',
    taskCards: 7,
    taskTokens: [],
    specialRule: true,
    taskNotes: [SpecialNotesEnum.COMMANDER_DISTRIBUTION],
  },
  {
    id: 33,
    note:
      'Der Kommandant bestimmt ein anderes Crewmitglied, dass genau einen Stich gewinnen muss - aber nicht mit einer Raketenkarte',
    taskCards: 0,
    taskTokens: [],
    taskNotes: [],
  },
  {
    id: 34,
    note:
      'Zu keinem Zeitpunkt darf ein Crewmitglied 2 Stiche mehr haben als ein anderes. Der Kommandant muss außerdem den ersten und den letzten Stich gewinnen.',
    taskCards: 0,
    taskTokens: [],
    taskNotes: [],
  },
  {
    id: 35,
    note: '',
    taskCards: 7,
    taskTokens: [
      TaskTokenEnum.TOKEN_BEFORE_1,
      TaskTokenEnum.TOKEN_BEFORE_2,
      TaskTokenEnum.TOKEN_BEFORE_3,
    ],
    specialRule: true,
    taskNotes: [],
  },
  {
    id: 36,
    note: '',
    taskCards: 7,
    taskTokens: [TaskTokenEnum.TOKEN_FIRST, TaskTokenEnum.TOKEN_SECOND],
    specialRule: true,
    taskNotes: [SpecialNotesEnum.COMMANDER_DISTRIBUTION],
  },
  {
    id: 37,
    note: '',
    taskCards: 4,
    taskTokens: [],
    specialRule: true,
    taskNotes: [SpecialNotesEnum.COMMANDER_DECISION],
  },
  {
    id: 38,
    note: '',
    taskCards: 8,
    taskTokens: [],
    specialRule: true,
    radioInterferenceAfter: 3,
    taskNotes: [SpecialNotesEnum.RADIO_INTERFERENCE],
  },
  {
    id: 39,
    note: '',
    taskCards: 8,
    taskTokens: [
      TaskTokenEnum.TOKEN_BEFORE_1,
      TaskTokenEnum.TOKEN_BEFORE_2,
      TaskTokenEnum.TOKEN_BEFORE_3,
    ],
    specialRule: true,
    taskNotes: [SpecialNotesEnum.RADIO_HOLE],
  },
  {
    id: 40,
    note:
      'Bevor ihr beginnt die Aufträge zu verteilen dürft ihr ein Auftragsplättchen zu einer Misson ohne Auftrag legen',
    taskCards: 8,
    taskTokens: [
      TaskTokenEnum.TOKEN_FIRST,
      TaskTokenEnum.TOKEN_SECOND,
      TaskTokenEnum.TOKEN_THIRD,
    ],
    specialRule: true,
    taskNotes: [],
  },
  {
    id: 41,
    note:
      'Der Kommandant bestimmt ein anderes Crewmitglied, dass genau den ersten und den letzten Stich gewinnt. Hierfür darf das Crewmitglied keine Raketenkarte benutzen.',
    taskCards: 0,
    taskTokens: [],
    taskNotes: [],
  },
  {
    id: 42,
    note: '',
    taskCards: 9,
    taskTokens: [],
    specialRule: true,
    taskNotes: [],
  },
  {
    id: 43,
    note: '',
    taskCards: 9,
    taskTokens: [],
    specialRule: true,
    taskNotes: [SpecialNotesEnum.COMMANDER_DISTRIBUTION],
  },
  {
    id: 44,
    note:
      'Die Raketenkarten müssen je einen Stich gewinnen. Als erstes die 1er Rakete, dann die 2er, 3er und zuletzt die 4er.',
    taskCards: 0,
    taskTokens: [],
    taskNotes: [],
  },
  {
    id: 45,
    note: '',
    taskCards: 9,
    taskTokens: [
      TaskTokenEnum.TOKEN_BEFORE_1,
      TaskTokenEnum.TOKEN_BEFORE_2,
      TaskTokenEnum.TOKEN_BEFORE_3,
    ],
    taskNotes: [],
    specialRule: true,
  },
  {
    id: 46,
    note:
      'Das Crewmitglied links von dem mit der roten 9 muss alle roten Karten gewinnen. Sagt an wer die rote 9 hat.',
    taskCards: 9,
    taskTokens: [],
    taskNotes: [],
  },
  {
    id: 47,
    note: '',
    taskCards: 10,
    taskTokens: [],
    specialRule: true,
    taskNotes: [],
  },
  {
    id: 48,
    note: 'Das Auftragsplätchen muss im letzten Stich erfüllt werden.',
    taskCards: 3,
    taskTokens: [TaskTokenEnum.TOKEN_LAST],
    taskNotes: [],
    specialRule: true,
  },
  {
    id: 49,
    note: '',
    taskCards: 10,
    taskTokens: [
      TaskTokenEnum.TOKEN_BEFORE_1,
      TaskTokenEnum.TOKEN_BEFORE_2,
      TaskTokenEnum.TOKEN_BEFORE_3,
    ],
    specialRule: true,
    taskNotes: [],
  },
  {
    id: 50,
    note:
      'Der Kommandant bestimmt. Eine Person muss die ersten 4 Stiche gewinnen. Ein anderes muss genau den letzten Stich gewinnen. Die restlichen Mitglieder müssen alle anderen Stiche gewinnen',
    taskCards: 0,
    taskTokens: [],
    taskNotes: [],
  },
];
