import {
  DeepSeaMissionInterface,
  SpaceMissionInterface,
  SpecialNotesEnum,
  TaskTokenEnum,
} from './interfaces';

const spaceMissions: SpaceMissionInterface[] = [
  {
    id: 1,
    note: '',
    taskCards: 1,
    taskTokens: [],
    taskNotes: [],
    gameType: 'space',
  },
  {
    id: 2,
    note: '',
    taskCards: 2,
    taskTokens: [],
    taskNotes: [],
    gameType: 'space',
  },
  {
    id: 3,
    taskCards: 2,
    note: '',
    taskTokens: [TaskTokenEnum.TOKEN_FIRST, TaskTokenEnum.TOKEN_SECOND],
    taskNotes: [],
    gameType: 'space',
  },
  {
    id: 4,
    note: '',
    taskCards: 3,
    taskTokens: [],
    taskNotes: [],
    gameType: 'space',
  },
  {
    id: 5,
    note: 'Der Kommandant fragt jedem nach seinem Befinden. Geantwortet mit "gut" oder "schlecht". Der Kommandant entscheidet wer krank ist. Diese Person darf keinen einzigen Stich gewinnen.',
    taskCards: 0,
    taskTokens: [],
    taskNotes: [],
    gameType: 'space',
  },
  {
    id: 6,
    note: '',
    taskCards: 3,
    taskTokens: [TaskTokenEnum.TOKEN_BEFORE_1, TaskTokenEnum.TOKEN_BEFORE_2],
    taskNotes: [SpecialNotesEnum.RADIO_HOLE],
    gameType: 'space',
  },
  {
    id: 7,
    note: '',
    taskCards: 3,
    taskTokens: [TaskTokenEnum.TOKEN_LAST],
    taskNotes: [],
    gameType: 'space',
  },
  {
    id: 8,
    note: '',
    taskCards: 3,
    taskTokens: [
      TaskTokenEnum.TOKEN_FIRST,
      TaskTokenEnum.TOKEN_SECOND,
      TaskTokenEnum.TOKEN_THIRD,
    ],
    taskNotes: [],
    gameType: 'space',
  },
  {
    id: 9,
    note: 'Eine 1er Karte muss einen Stich gewinnen.',
    taskCards: 1,
    taskTokens: [],
    taskNotes: [],
    gameType: 'space',
  },
  {
    id: 10,
    note: '',
    taskCards: 4,
    taskTokens: [],
    taskNotes: [],
    gameType: 'space',
  },
  {
    id: 11,
    note: 'Ein Crewmitglied kann nicht kommunizieren. Der Kommandant bestimmt das Crewmitglied.',
    taskCards: 4,
    taskTokens: [TaskTokenEnum.TOKEN_FIRST],
    taskNotes: [],

    gameType: 'space',
  },
  {
    id: 12,
    note: 'Nach dem 1. Stich muss jeder eine zufällige Karte des Crewmitglieds rechts von sich ziehen.',
    taskCards: 4,
    taskTokens: [TaskTokenEnum.TOKEN_LAST],
    taskNotes: [],

    gameType: 'space',
  },
  {
    id: 13,
    note: 'Ihr müsst mit jeder Raketenkarte einen Stich gewinnen.',
    taskCards: 0,
    taskTokens: [],
    taskNotes: [],
    gameType: 'space',
  },
  {
    id: 14,
    note: '',
    taskCards: 4,
    taskTokens: [
      TaskTokenEnum.TOKEN_BEFORE_1,
      TaskTokenEnum.TOKEN_BEFORE_2,
      TaskTokenEnum.TOKEN_BEFORE_3,
    ],
    taskNotes: [SpecialNotesEnum.RADIO_HOLE],
    gameType: 'space',
  },
  {
    id: 15,
    note: '',
    taskCards: 4,
    taskTokens: [
      TaskTokenEnum.TOKEN_FIRST,
      TaskTokenEnum.TOKEN_SECOND,
      TaskTokenEnum.TOKEN_THIRD,
      TaskTokenEnum.TOKEN_FOURTH,
    ],
    taskNotes: [],
    gameType: 'space',
  },
  {
    id: 16,
    note: 'Ihr dürft keinen Stich mit einer 9er Karte gewinnen.',
    taskCards: 0,
    taskTokens: [],
    taskNotes: [],
    gameType: 'space',
  },
  {
    id: 17,
    note: '9er Karten gewinnen noch immer keinen Stich.',
    taskCards: 2,
    taskTokens: [],
    taskNotes: [],
    gameType: 'space',
  },
  {
    id: 18,
    note: '',
    taskCards: 5,
    taskTokens: [],
    taskNotes: [SpecialNotesEnum.RADIO_INTERFERENCE],
    radioInterferenceAfter: 2,
    gameType: 'space',
  },
  {
    id: 19,
    note: '',
    taskCards: 5,
    taskTokens: [TaskTokenEnum.TOKEN_FIRST],
    taskNotes: [SpecialNotesEnum.RADIO_INTERFERENCE],
    radioInterferenceAfter: 3,
    gameType: 'space',
  },
  {
    id: 20,
    note: '',
    taskCards: 2,
    taskTokens: [],
    taskNotes: [SpecialNotesEnum.COMMANDER_DECISION],
    gameType: 'space',
  },
  {
    id: 21,
    note: '',
    taskCards: 5,
    taskTokens: [TaskTokenEnum.TOKEN_FIRST, TaskTokenEnum.TOKEN_SECOND],
    taskNotes: [SpecialNotesEnum.RADIO_HOLE],
    gameType: 'space',
  },
  {
    id: 22,
    note: '',
    taskCards: 5,
    taskTokens: [
      TaskTokenEnum.TOKEN_BEFORE_1,
      TaskTokenEnum.TOKEN_BEFORE_2,
      TaskTokenEnum.TOKEN_BEFORE_3,
      TaskTokenEnum.TOKEN_BEFORE_4,
    ],
    taskNotes: [],
    gameType: 'space',
  },
  {
    id: 23,
    note: 'Bevor die Aufträge verteilt werden dürft ihr zwei Auftragsplättchen tauschen. Entscheidet gemeinsam, aber verratet nichts über eure Handkarten.',
    taskCards: 5,
    taskTokens: [
      TaskTokenEnum.TOKEN_FIRST,
      TaskTokenEnum.TOKEN_SECOND,
      TaskTokenEnum.TOKEN_THIRD,
      TaskTokenEnum.TOKEN_FOURTH,
      TaskTokenEnum.TOKEN_FIFTH,
    ],
    taskNotes: [],
    gameType: 'space',
  },
  {
    id: 24,
    note: '',
    taskCards: 6,
    taskTokens: [],
    taskNotes: [SpecialNotesEnum.COMMANDER_DISTRIBUTION],
    gameType: 'space',
  },
  {
    id: 25,
    note: 'Spielt ihr zu fünft darf ab jetzt die Zusatzregel für 5 Crewmitglieder genutzt werden.',
    taskCards: 6,
    taskTokens: [TaskTokenEnum.TOKEN_BEFORE_1, TaskTokenEnum.TOKEN_BEFORE_2],
    taskNotes: [SpecialNotesEnum.RADIO_HOLE],
    specialRule: true,
    gameType: 'space',
  },
  {
    id: 26,
    note: 'Zwei 1er Karten müssen einen Stich gewinnen',
    taskCards: 0,
    taskTokens: [],
    taskNotes: [],
    gameType: 'space',
  },
  {
    id: 27,
    note: '',
    taskCards: 3,
    taskTokens: [],
    specialRule: true,
    taskNotes: [SpecialNotesEnum.COMMANDER_DECISION],
    gameType: 'space',
  },
  {
    id: 28,
    note: '',
    taskCards: 6,
    taskTokens: [TaskTokenEnum.TOKEN_FIRST, TaskTokenEnum.TOKEN_LAST],
    taskNotes: [SpecialNotesEnum.RADIO_INTERFERENCE],
    radioInterferenceAfter: 3,
    specialRule: true,
    gameType: 'space',
  },
  {
    id: 29,
    note: 'Zu keinen Zeitpunkt darf ein Crewmitgleid 2 Stiche mehr haben als ein anderes.',
    taskCards: 0,
    taskTokens: [],
    taskNotes: [SpecialNotesEnum.RADIO_HOLE],
    gameType: 'space',
  },
  {
    id: 30,
    note: '',
    taskCards: 6,
    taskTokens: [
      TaskTokenEnum.TOKEN_BEFORE_1,
      TaskTokenEnum.TOKEN_BEFORE_2,
      TaskTokenEnum.TOKEN_BEFORE_3,
    ],
    specialRule: true,
    taskNotes: [SpecialNotesEnum.RADIO_INTERFERENCE],
    radioInterferenceAfter: 2,
    gameType: 'space',
  },
  {
    id: 31,
    note: '',
    taskCards: 6,
    taskTokens: [
      TaskTokenEnum.TOKEN_FIRST,
      TaskTokenEnum.TOKEN_SECOND,
      TaskTokenEnum.TOKEN_THIRD,
    ],
    specialRule: true,
    taskNotes: [],
    gameType: 'space',
  },
  {
    id: 32,
    note: '',
    taskCards: 7,
    taskTokens: [],
    specialRule: true,
    taskNotes: [SpecialNotesEnum.COMMANDER_DISTRIBUTION],
    gameType: 'space',
  },
  {
    id: 33,
    note: 'Der Kommandant bestimmt ein anderes Crewmitglied, dass genau einen Stich gewinnen muss - aber nicht mit einer Raketenkarte',
    taskCards: 0,
    taskTokens: [],
    taskNotes: [],
    gameType: 'space',
  },
  {
    id: 34,
    note: 'Zu keinem Zeitpunkt darf ein Crewmitglied 2 Stiche mehr haben als ein anderes. Der Kommandant muss außerdem den ersten und den letzten Stich gewinnen.',
    taskCards: 0,
    taskTokens: [],
    taskNotes: [],
    gameType: 'space',
  },
  {
    id: 35,
    note: '',
    taskCards: 7,
    taskTokens: [
      TaskTokenEnum.TOKEN_BEFORE_1,
      TaskTokenEnum.TOKEN_BEFORE_2,
      TaskTokenEnum.TOKEN_BEFORE_3,
    ],
    specialRule: true,
    taskNotes: [],
    gameType: 'space',
  },
  {
    id: 36,
    note: '',
    taskCards: 7,
    taskTokens: [TaskTokenEnum.TOKEN_FIRST, TaskTokenEnum.TOKEN_SECOND],
    specialRule: true,
    taskNotes: [SpecialNotesEnum.COMMANDER_DISTRIBUTION],
    gameType: 'space',
  },
  {
    id: 37,
    note: '',
    taskCards: 4,
    taskTokens: [],
    specialRule: true,
    taskNotes: [SpecialNotesEnum.COMMANDER_DECISION],
    gameType: 'space',
  },
  {
    id: 38,
    note: '',
    taskCards: 8,
    taskTokens: [],
    specialRule: true,
    radioInterferenceAfter: 3,
    taskNotes: [SpecialNotesEnum.RADIO_INTERFERENCE],
    gameType: 'space',
  },
  {
    id: 39,
    note: '',
    taskCards: 8,
    taskTokens: [
      TaskTokenEnum.TOKEN_BEFORE_1,
      TaskTokenEnum.TOKEN_BEFORE_2,
      TaskTokenEnum.TOKEN_BEFORE_3,
    ],
    specialRule: true,
    taskNotes: [SpecialNotesEnum.RADIO_HOLE],
    gameType: 'space',
  },
  {
    id: 40,
    note: 'Bevor ihr beginnt die Aufträge zu verteilen dürft ihr ein Auftragsplättchen zu einer Misson ohne Auftrag legen',
    taskCards: 8,
    taskTokens: [
      TaskTokenEnum.TOKEN_FIRST,
      TaskTokenEnum.TOKEN_SECOND,
      TaskTokenEnum.TOKEN_THIRD,
    ],
    specialRule: true,
    taskNotes: [],
    gameType: 'space',
  },
  {
    id: 41,
    note: 'Der Kommandant bestimmt ein anderes Crewmitglied, dass genau den ersten und den letzten Stich gewinnt. Hierfür darf das Crewmitglied keine Raketenkarte benutzen.',
    taskCards: 0,
    taskTokens: [],
    taskNotes: [],
    gameType: 'space',
  },
  {
    id: 42,
    note: '',
    taskCards: 9,
    taskTokens: [],
    specialRule: true,
    taskNotes: [],
    gameType: 'space',
  },
  {
    id: 43,
    note: '',
    taskCards: 9,
    taskTokens: [],
    specialRule: true,
    taskNotes: [SpecialNotesEnum.COMMANDER_DISTRIBUTION],
    gameType: 'space',
  },
  {
    id: 44,
    note: 'Die Raketenkarten müssen je einen Stich gewinnen. Als erstes die 1er Rakete, dann die 2er, 3er und zuletzt die 4er.',
    taskCards: 0,
    taskTokens: [],
    taskNotes: [],

    gameType: 'space',
  },
  {
    id: 45,
    note: '',
    taskCards: 9,
    taskTokens: [
      TaskTokenEnum.TOKEN_BEFORE_1,
      TaskTokenEnum.TOKEN_BEFORE_2,
      TaskTokenEnum.TOKEN_BEFORE_3,
    ],
    taskNotes: [],
    specialRule: true,
    gameType: 'space',
  },
  {
    id: 46,
    note: 'Das Crewmitglied links von dem mit der roten 9 muss alle roten Karten gewinnen. Sagt an wer die rote 9 hat.',
    taskCards: 9,
    taskTokens: [],
    taskNotes: [],
    gameType: 'space',
  },
  {
    id: 47,
    note: '',
    taskCards: 10,
    taskTokens: [],
    specialRule: true,
    taskNotes: [],
    gameType: 'space',
  },
  {
    id: 48,
    note: 'Das Auftragsplätchen muss im letzten Stich erfüllt werden.',
    taskCards: 3,
    taskTokens: [TaskTokenEnum.TOKEN_LAST],
    taskNotes: [],
    specialRule: true,
    gameType: 'space',
  },
  {
    id: 49,
    note: '',
    taskCards: 10,
    taskTokens: [
      TaskTokenEnum.TOKEN_BEFORE_1,
      TaskTokenEnum.TOKEN_BEFORE_2,
      TaskTokenEnum.TOKEN_BEFORE_3,
    ],
    specialRule: true,
    taskNotes: [],
    gameType: 'space',
  },
  {
    id: 50,
    note: 'Der Kommandant bestimmt. Eine Person muss die ersten 4 Stiche gewinnen. Ein anderes muss genau den letzten Stich gewinnen. Die restlichen Mitglieder müssen alle anderen Stiche gewinnen',
    taskCards: 0,
    taskTokens: [],
    taskNotes: [],
    gameType: 'space',
  },
];

const deepSeaMissions: DeepSeaMissionInterface[] = [
  {
    id: 1,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 1,
    note: '',
    taskNotes: [],
  },
  {
    id: 2,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 2,
    note: '',
    taskNotes: [],
  },
  {
    id: 3,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 3,
    note: '',
    taskNotes: [],
  },
  {
    id: 4,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 4,
    note: '',
    taskNotes: [],
  },
  {
    id: 5,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 5,
    note: '',
    taskNotes: [],
  },
  {
    id: 6,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 5,
    note: 'Entscheidet gemeinsam, welches Crewmitglied alle Aufträge übernimmt aber verratet nichts über eure Handkarten.',
    taskNotes: [],
  },
  {
    id: 7,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 6,
    note: '',
    taskNotes: [],
  },
  {
    id: 8,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 0,
    note: 'Zu keinem Zeitpunkt darf ein Crewmitglied zwei 9-er Karten mehr als ein anderes Crewmitglied gewonnen haben.',
    taskNotes: [],
  },
  {
    id: 9,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 7,
    note: '',
    taskNotes: [SpecialNotesEnum.RADIO_FLOW],
  },
  {
    id: 10,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 4,
    note: "Euer Käpt'n übernimmt alle Aufträge oder gibt alle an ein freiwilliges Crewmitglied ab. Werden sie abgegeben, muss jeder vor dem ersten Stich kommunizieren.",
    taskNotes: [],
  },
  {
    id: 11,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 8,
    note: '',
    taskNotes: [SpecialNotesEnum.RADIO_DEPTH_RAGE],
  },
  {
    id: 12,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 0,
    note: 'Kein Stich darf mit einer roten oder einer U-Boot-Karte eröffnet werden.',
    taskNotes: [],
  },
  {
    id: 13,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 5,
    note: "Euer Käpt'n übernimmt alle Aufträge oder gibt alle an ein freiwilliges Crewmitglied ab. Werden sie abgegeben, muss jeder vor dem ersten Stich kommunizieren.",
    taskNotes: [],
  },
  {
    id: 14,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 6,
    note: 'Ihr habt 3:30 Minuten Zeit, die Aufträge zu erfüllen. Spielt ihr ohne Zeitbegrenzung, gilt stattdessen die Strömungs-Regel.',
    taskNotes: [SpecialNotesEnum.REALTIME],
  },
  {
    id: 15,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 6,
    note: 'Ihr habt 3:00 Minuten Zeit, die Aufträge zu erfüllen. Spielt ihr ohne Zeitbegrenzung, gilt stattdessen die Tiefenrausch-Regel.',
    taskNotes: [SpecialNotesEnum.REALTIME],
  },
  {
    id: 16,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 6,
    note: 'Ihr habt 2:30 Minuten Zeit, die Aufträge zu erfüllen. Spielt ihr ohne Zeitbegrenzung, ist stattdessen gar keine Kommunikation erlaubt.',
    taskNotes: [SpecialNotesEnum.REALTIME],
  },
  {
    id: 17,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 9,
    note: 'Es gilt die freie Auftragswahl',
    taskNotes: [SpecialNotesEnum.FREE_ORDER_CHOICE],
  },
  {
    id: 18,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 9,
    note: '',
    taskNotes: [],
  },
  {
    id: 19,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 9,
    note: "Euer Käpt'n muss als ersten Auftrag einen der ausliegenden Aufträge mit dem höchsten Schwierigkeitsgrad nehmen. Die übrigen Aufträge wählt ihr wie gewohnt im Uhrzeigersinn aus.",
    taskNotes: [],
  },
  {
    id: 20,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 10,
    note: '',
    taskNotes: [SpecialNotesEnum.RADIO_UNKNOWN_TERRAIN],
  },
  {
    id: 21,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 0,
    note: 'Zu keinem Zeitpunkt darf ein Crewmitglied zwei 1er Farbkarten mehr als ein anderes Crewmitglied gewonnen haben.',
    taskNotes: [SpecialNotesEnum.RADIO_UNKNOWN_TERRAIN],
  },
  {
    id: 22,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 11,
    note: '',
    taskNotes: [SpecialNotesEnum.RADIO_UNKNOWN_TERRAIN],
  },
  {
    id: 23,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 0,
    note: 'Wer den ersten Stich gewinnt, muss zu jedem Zeitpunkt mehr Stiche gewonnen haben, als jedes andere Crewmitglied. Ihr dürft erst zum zweiten Stich (also direkt davor) kommunizieren.',
    taskNotes: [SpecialNotesEnum.RADIO_UNKNOWN_TERRAIN],
  },
  {
    id: 24,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 12,
    note: '',
    taskNotes: [SpecialNotesEnum.RADIO_UNKNOWN_TERRAIN],
  },
  {
    id: 25,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 12,
    note: "Wählt die Aufträge wie gewohnt im Uhrzeigersinn. Euer Käpt'n wird allerdings immer übersprungen und erhält daher keine Aufträge.",
    taskNotes: [SpecialNotesEnum.RADIO_UNKNOWN_TERRAIN],
  },
  {
    id: 26,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 10,
    note: 'Ihr habt 5:00 Minuten Zeit, die Aufträge zu erfüllen. Spielt Ihr ohne Zeitbegrenzung, steigt der Gesamt-Schwierigkeitsgrad auf 12.',
    taskNotes: [
      SpecialNotesEnum.RADIO_UNKNOWN_TERRAIN,
      SpecialNotesEnum.REALTIME,
    ],
  },
  {
    id: 27,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 0,
    note: 'Die gelbe 5 muss als letzte Karte im letzten Strich der gesamten Mission ausgespielt werden. Im Spiel zu dritt darf Sie also nicht übrig bleiben.',
    taskNotes: [SpecialNotesEnum.RADIO_UNKNOWN_TERRAIN],
  },
  {
    id: 28,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 14,
    note: '',
    taskNotes: [SpecialNotesEnum.FREE_ORDER_CHOICE],
  },
  {
    id: 29,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 15,
    note: '',
    taskNotes: [SpecialNotesEnum.FREE_ORDER_CHOICE],
  },
  {
    id: 30,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 16,
    note: '',
    taskNotes: [SpecialNotesEnum.FREE_ORDER_CHOICE],
  },
  {
    id: 31,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 17,
    note: '',
    taskNotes: [SpecialNotesEnum.FREE_ORDER_CHOICE],
  },
  {
    id: 32,
    gameType: 'deepSea',
    taskTokens: [],
    taskCards: 0,
    note: 'Nehmt für die Mission die folgenden Auftragskarten und wählt Sie wie gewohnt im Uhrzeigersinn: "Ich gewinne 0 Stiche", "Ich gewinne genau 3 Stiche in Folge", "Ich gewinne 2 Stiche in Folge" und "Ich gewinne den ersten und letzten Stich".',
    taskNotes: [],
  },
];

const allMissions = [...spaceMissions, ...deepSeaMissions];
export default allMissions;
